#!/system/bin/sh
echo 0 > /sys/android_touch/wake_gestures #1 to turn off all
echo 1 > /sys/android_touch/pocket_detect
echo 4 > /sys/android_touch/sweep2wake ## 1 to enable sweep right, 2 to enable sweep left, 4 up, 8 down, For combinations, add values together (e.g. all gestures enabled = 15)
echo 1 > /sys/android_touch/doubletap2wake
echo 3 > /sys/android_touch/sweep2sleep
echo 1 > /sys/android_touch/camera_gesture


